// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexico.flex

/* ===================================================================
   Lexico.flex - Primera entrega - Teoria de la Computacion I - UNLu
   Grupo 2 - Tema especial: PRINCIPIO
   (Archivo en ASCII a proposito: JFlex lo lee con la codificacion
   por defecto del sistema, por eso no hay tildes ni enes aca.)
   =================================================================== */
package compilador;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\2\2\22\0\1\1\1\3"+
    "\1\4\2\0\1\5\2\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\12\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\0\1\5\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\2\25\1\35\1\36"+
    "\1\37\1\40\1\41\1\25\1\42\1\43\1\44\2\25"+
    "\1\45\3\25\1\46\1\0\1\47\3\0\32\25\1\50"+
    "\1\0\1\51\43\0\1\5\57\0\1\5\37\0\1\5"+
    "\u010e\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\1\16\1\1\1\17\13\20\1\21\1\22\1\23\1\24"+
    "\3\25\1\26\1\0\1\27\1\0\1\30\2\0\1\31"+
    "\1\32\1\33\1\34\5\20\1\35\1\20\1\36\5\20"+
    "\2\0\1\37\1\40\1\41\1\42\4\20\1\43\6\20"+
    "\1\44\1\45\1\20\1\46\10\20\1\47\4\20\1\50"+
    "\2\20\1\51\3\20\1\52\1\53\6\20\1\54\6\20"+
    "\1\0\2\20\1\55\1\20\2\0\2\20\1\56\2\0"+
    "\2\20\21\0\1\57\2\0\1\60\4\0\1\61\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\124\0\124"+
    "\0\374\0\124\0\124\0\124\0\u0126\0\u0150\0\u017a\0\u01a4"+
    "\0\124\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca"+
    "\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0\0\124"+
    "\0\124\0\124\0\124\0\124\0\u041a\0\u0444\0\124\0\322"+
    "\0\124\0\u046e\0\u0126\0\u0498\0\u04c2\0\124\0\124\0\124"+
    "\0\124\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594\0\u0276\0\u05be"+
    "\0\u0276\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4"+
    "\0\124\0\124\0\124\0\u0276\0\u070e\0\u0738\0\u0762\0\u078c"+
    "\0\u0276\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888\0\124"+
    "\0\124\0\u08b2\0\u0276\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984"+
    "\0\u09ae\0\u09d8\0\u0a02\0\u0276\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa"+
    "\0\u0276\0\u0ad4\0\u0afe\0\u0276\0\u0b28\0\u0b52\0\u0b7c\0\u0276"+
    "\0\u0276\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78\0\u0276"+
    "\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\u0dc8"+
    "\0\u0df2\0\u0276\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0276"+
    "\0\u0eee\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014"+
    "\0\u103e\0\u1068\0\u1092\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164"+
    "\0\u118e\0\u11b8\0\u11e2\0\u120c\0\u1236\0\124\0\u1260\0\u128a"+
    "\0\124\0\u12b4\0\u12de\0\u1308\0\u1332\0\124\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\2\26\1\27\1\30\1\31"+
    "\2\26\1\32\3\26\1\33\1\34\1\26\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\10\44\1\45\4\44"+
    "\1\46\34\44\53\0\2\4\71\0\1\47\30\0\1\50"+
    "\1\0\1\50\1\51\1\50\2\0\36\50\21\0\1\52"+
    "\52\0\1\53\50\0\1\54\50\0\1\53\1\0\1\17"+
    "\52\0\1\55\2\0\1\56\51\0\1\57\51\0\1\60"+
    "\51\0\1\61\45\0\1\26\5\0\13\26\1\62\6\26"+
    "\22\0\1\26\5\0\22\26\22\0\1\26\5\0\4\26"+
    "\1\63\15\26\22\0\1\26\5\0\11\26\1\64\1\26"+
    "\1\65\6\26\22\0\1\26\5\0\11\26\1\66\10\26"+
    "\22\0\1\26\5\0\5\26\1\67\5\26\1\70\6\26"+
    "\22\0\1\26\5\0\16\26\1\71\3\26\22\0\1\26"+
    "\5\0\16\26\1\72\3\26\22\0\1\26\5\0\20\26"+
    "\1\73\1\26\22\0\1\26\5\0\7\26\1\74\12\26"+
    "\22\0\1\26\5\0\7\26\1\75\6\26\1\76\3\26"+
    "\21\0\1\77\51\0\1\100\51\0\1\101\44\0\1\102"+
    "\63\0\1\103\45\0\1\26\5\0\3\26\1\104\16\26"+
    "\22\0\1\26\5\0\2\26\1\105\17\26\22\0\1\26"+
    "\5\0\17\26\1\106\2\26\22\0\1\26\5\0\3\26"+
    "\1\107\16\26\22\0\1\26\5\0\14\26\1\110\5\26"+
    "\22\0\1\26\5\0\20\26\1\111\1\26\22\0\1\26"+
    "\5\0\10\26\1\112\3\26\1\113\5\26\22\0\1\26"+
    "\5\0\16\26\1\114\3\26\22\0\1\26\5\0\4\26"+
    "\1\115\15\26\22\0\1\26\5\0\10\26\1\116\11\26"+
    "\22\0\1\26\5\0\10\26\1\117\11\26\21\0\1\120"+
    "\44\0\1\121\57\0\1\26\5\0\11\26\1\122\10\26"+
    "\22\0\1\26\5\0\4\26\1\123\15\26\22\0\1\26"+
    "\5\0\3\26\1\124\4\26\1\125\4\26\1\126\3\26"+
    "\1\127\22\0\1\26\5\0\1\130\21\26\22\0\1\26"+
    "\5\0\13\26\1\131\6\26\22\0\1\26\5\0\6\26"+
    "\1\132\13\26\22\0\1\26\5\0\10\26\1\133\11\26"+
    "\22\0\1\26\5\0\13\26\1\134\6\26\22\0\1\26"+
    "\5\0\11\26\1\135\10\26\22\0\1\26\5\0\20\26"+
    "\1\136\1\26\22\0\1\26\5\0\1\137\21\26\22\0"+
    "\1\26\5\0\4\26\1\140\15\26\22\0\1\26\5\0"+
    "\5\26\1\141\14\26\22\0\1\26\5\0\16\26\1\142"+
    "\3\26\22\0\1\26\5\0\7\26\1\143\12\26\22\0"+
    "\1\26\5\0\20\26\1\144\1\26\22\0\1\26\5\0"+
    "\2\26\1\145\17\26\22\0\1\26\5\0\16\26\1\146"+
    "\3\26\22\0\1\26\5\0\13\26\1\147\6\26\22\0"+
    "\1\26\5\0\4\26\1\150\15\26\22\0\1\26\5\0"+
    "\4\26\1\151\15\26\22\0\1\26\5\0\16\26\1\152"+
    "\3\26\22\0\1\26\5\0\2\26\1\153\17\26\22\0"+
    "\1\26\5\0\14\26\1\154\5\26\22\0\1\26\5\0"+
    "\10\26\1\155\11\26\22\0\1\26\5\0\10\26\1\156"+
    "\11\26\22\0\1\26\5\0\1\157\21\26\22\0\1\26"+
    "\5\0\6\26\1\160\13\26\22\0\1\26\5\0\4\26"+
    "\1\161\15\26\22\0\1\26\5\0\11\26\1\162\10\26"+
    "\22\0\1\26\5\0\6\26\1\163\13\26\22\0\1\26"+
    "\5\0\11\26\1\164\10\26\22\0\1\26\5\0\15\26"+
    "\1\165\4\26\22\0\1\26\5\0\12\26\1\166\7\26"+
    "\20\0\1\167\1\0\1\26\5\0\22\26\22\0\1\26"+
    "\5\0\1\170\21\26\22\0\1\26\5\0\16\26\1\171"+
    "\3\26\22\0\1\26\5\0\4\26\1\172\15\26\22\0"+
    "\1\26\5\0\10\26\1\173\11\26\20\0\1\174\1\0"+
    "\1\26\5\0\22\26\47\0\1\175\24\0\1\26\5\0"+
    "\16\26\1\176\3\26\22\0\1\26\5\0\1\177\21\26"+
    "\22\0\1\26\5\0\14\26\1\200\5\26\47\0\1\201"+
    "\36\0\1\202\37\0\1\26\5\0\4\26\1\203\15\26"+
    "\22\0\1\26\5\0\12\26\1\204\7\26\34\0\1\205"+
    "\47\0\1\206\37\0\1\207\1\0\1\26\5\0\22\26"+
    "\20\0\1\210\1\0\1\26\5\0\22\26\32\0\1\211"+
    "\67\0\1\212\50\0\1\213\51\0\1\214\52\0\1\215"+
    "\41\0\1\216\45\0\1\217\51\0\1\220\55\0\1\221"+
    "\55\0\1\222\37\0\1\223\51\0\1\224\63\0\1\225"+
    "\50\0\1\226\56\0\1\227\51\0\1\230\44\0\1\231"+
    "\46\0\1\232\51\0\1\233\55\0\1\234\51\0\1\235"+
    "\50\0\1\236\51\0\1\237\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4956];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\2\11\1\1\3\11\4\1\1\11"+
    "\16\1\5\11\2\1\1\11\1\0\1\11\1\0\1\1"+
    "\2\0\4\11\15\1\2\0\3\11\14\1\2\11\45\1"+
    "\1\0\4\1\2\0\3\1\2\0\2\1\21\0\1\11"+
    "\2\0\1\11\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* Tabla de simbolos que se va llenando durante el analisis */
    public TablaSimbolos tabla = new TablaSimbolos();

    /* Control de comentarios (se admite un solo nivel de anidamiento) */
    private int nivelComentario = 0;
    private int lineaInicioComentario = 0;

    private Token tok(String nombre) {
        return new Token(nombre, yytext(), yyline + 1, yycolumn + 1);
    }

    private ErrorLexico error(String mensaje) {
        return new ErrorLexico(mensaje, yyline + 1, yycolumn + 1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return null;
            }  // fall though
            case 160: break;
            case COMENT: {
              throw new ErrorLexico("Comentario sin cerrar (abierto en la linea "
                                   + lineaInicioComentario + ")", yyline + 1, yycolumn + 1);
            }  // fall though
            case 161: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw error("Caracter no permitido: <" + yytext() + ">");
            }
            // fall through
          case 51: break;
          case 2:
            { /* no genera token ni salida */
            }
            // fall through
          case 52: break;
          case 3:
            { throw error("String mal formado (sin cerrar, con caracter no permitido o con salto de linea)");
            }
            // fall through
          case 53: break;
          case 4:
            { return tok("PAR_A");
            }
            // fall through
          case 54: break;
          case 5:
            { return tok("PAR_C");
            }
            // fall through
          case 55: break;
          case 6:
            { return tok("OP_MULT");
            }
            // fall through
          case 56: break;
          case 7:
            { return tok("OP_SUMA");
            }
            // fall through
          case 57: break;
          case 8:
            { return tok("COMA");
            }
            // fall through
          case 58: break;
          case 9:
            { return tok("OP_RESTA");
            }
            // fall through
          case 59: break;
          case 10:
            { return tok("PUNTO");
            }
            // fall through
          case 60: break;
          case 11:
            { return tok("OP_DIV");
            }
            // fall through
          case 61: break;
          case 12:
            { if (new java.math.BigInteger(yytext())
                                       .compareTo(java.math.BigInteger.valueOf(32767)) > 0)
                                   throw error("Constante entera fuera de rango (0..32767): " + yytext());
                               tabla.agregarCteE(yytext());
                               return tok("CTE_E");
            }
            // fall through
          case 62: break;
          case 13:
            { return tok("PUNTO_Y_COMA");
            }
            // fall through
          case 63: break;
          case 14:
            { return tok("OP_MENOR");
            }
            // fall through
          case 64: break;
          case 15:
            { return tok("OP_MAYOR");
            }
            // fall through
          case 65: break;
          case 16:
            { tabla.agregarID(yytext());
                               return tok("ID");
            }
            // fall through
          case 66: break;
          case 17:
            { return tok("COR_A");
            }
            // fall through
          case 67: break;
          case 18:
            { return tok("COR_C");
            }
            // fall through
          case 68: break;
          case 19:
            { return tok("LLAV_A");
            }
            // fall through
          case 69: break;
          case 20:
            { return tok("LLAV_C");
            }
            // fall through
          case 70: break;
          case 21:
            { /* el contenido del comentario se ignora */
            }
            // fall through
          case 71: break;
          case 22:
            { return tok("OP_DISTINTO");
            }
            // fall through
          case 72: break;
          case 23:
            { String valor = yytext().substring(1, yytext().length() - 1);
                               if (valor.length() > 30)
                                   throw error("String de mas de 30 caracteres (" + valor.length() + "): " + yytext());
                               tabla.agregarCteStr(valor);
                               return tok("CTE_STR");
            }
            // fall through
          case 73: break;
          case 24:
            { float f = Float.parseFloat(yytext());
                               if (Float.isInfinite(f))
                                   throw error("Constante real fuera de rango (32 bits): " + yytext());
                               tabla.agregarCteF(yytext());
                               return tok("CTE_F");
            }
            // fall through
          case 74: break;
          case 25:
            { return tok("ASIG_DECL");
            }
            // fall through
          case 75: break;
          case 26:
            { return tok("OP_MENOR_IGUAL");
            }
            // fall through
          case 76: break;
          case 27:
            { return tok("OP_IGUAL");
            }
            // fall through
          case 77: break;
          case 28:
            { return tok("OP_MAYOR_IGUAL");
            }
            // fall through
          case 78: break;
          case 29:
            { return tok("IF");
            }
            // fall through
          case 79: break;
          case 30:
            { return tok("OR");
            }
            // fall through
          case 80: break;
          case 31:
            { throw error("Cierre de comentario '*//' sin apertura");
            }
            // fall through
          case 81: break;
          case 32:
            { nivelComentario = 1;
                               lineaInicioComentario = yyline + 1;
                               yybegin(COMENT);
            }
            // fall through
          case 82: break;
          case 33:
            { return tok("ASIGNACION");
            }
            // fall through
          case 83: break;
          case 34:
            { return tok("AND");
            }
            // fall through
          case 84: break;
          case 35:
            { return tok("INTEGER");
            }
            // fall through
          case 85: break;
          case 36:
            { nivelComentario--;
                               if (nivelComentario == 0) yybegin(YYINITIAL);
            }
            // fall through
          case 86: break;
          case 37:
            { if (nivelComentario == 1) {
                                   nivelComentario = 2;
                               } else {
                                   throw error("Los comentarios solo pueden anidarse un nivel");
                               }
            }
            // fall through
          case 87: break;
          case 38:
            { return tok("ELSE");
            }
            // fall through
          case 88: break;
          case 39:
            { return tok("THEN");
            }
            // fall through
          case 89: break;
          case 40:
            { return tok("ENDIF");
            }
            // fall through
          case 90: break;
          case 41:
            { return tok("FLOAT");
            }
            // fall through
          case 91: break;
          case 42:
            { return tok("WHILE");
            }
            // fall through
          case 92: break;
          case 43:
            { return tok("WRITE");
            }
            // fall through
          case 93: break;
          case 44:
            { return tok("STRING");
            }
            // fall through
          case 94: break;
          case 45:
            { return tok("ENDWHILE");
            }
            // fall through
          case 95: break;
          case 46:
            { return tok("PRINCIPIO");
            }
            // fall through
          case 96: break;
          case 47:
            { return tok("DECLARE_SECTION");
            }
            // fall through
          case 97: break;
          case 48:
            { return tok("PROGRAM_SECTION");
            }
            // fall through
          case 98: break;
          case 49:
            { return tok("ENDDECLARE_SECTION");
            }
            // fall through
          case 99: break;
          case 50:
            { return tok("ENDPROGRAM_SECTION");
            }
            // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
